# Makefile for temporal_cache TYPO3 Extension
# Auto-generated by ddev setup - Last updated: 2025-10-29

.PHONY: help
help: ## Show available targets
	@awk 'BEGIN{FS=":.*##";print "\nUsage: make <target>\n"} /^[a-zA-Z0-9_.-]+:.*##/ {printf "  %-22s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# ===================================
# DDEV Environment Commands
# ===================================

.PHONY: up
up: start setup ## Complete startup (start DDEV + run setup) - ONE COMMAND TO RULE THEM ALL

.PHONY: start
start: ## Start DDEV environment
	ddev start

.PHONY: stop
stop: ## Stop DDEV environment
	ddev stop

.PHONY: setup
setup: ## Complete setup (install all TYPO3 versions)
	@ddev describe >/dev/null 2>&1 || ddev start
	ddev install-all

.PHONY: install-v12
install-v12: ## Install TYPO3 v12.4 LTS with extension
	ddev install-v12

.PHONY: install-v13
install-v13: ## Install TYPO3 v13.0 LTS with extension
	ddev install-v13

.PHONY: install-all
install-all: ## Install all TYPO3 versions (v12 and v13)
	ddev install-all

.PHONY: ddev-restart
ddev-restart: ## Restart DDEV containers
	ddev restart

.PHONY: ssh
ssh: ## SSH into DDEV web container
	ddev ssh

# ===================================
# Composer & Quality Commands
# ===================================

.PHONY: install
install: ## Install composer dependencies
	composer install

.PHONY: lint
lint: ## Run all linters (PHP syntax + PHPStan + code style)
	@echo "==> Running PHP lint..."
	composer ci:test:php:lint || composer lint
	@echo "==> Running PHPStan..."
	composer phpstan || composer ci:phpstan || echo "⚠️  PHPStan not configured"
	@echo "==> Running code style check..."
	composer ci:test:php:cgl || composer cs:check || echo "⚠️  Code style check not configured"
	@echo "✅ All linters passed"

.PHONY: format
format: ## Auto-fix code style issues (PSR-12)
	composer code:fix || composer cs:fix

.PHONY: typecheck
typecheck: ## Run PHPStan static analysis
	composer phpstan || composer ci:phpstan

.PHONY: test
test: ## Run all tests (unit + functional)
	composer test

.PHONY: test-unit
test-unit: ## Run unit tests only
	composer test:unit

.PHONY: test-functional
test-functional: ## Run functional tests
	composer test:functional

.PHONY: test-coverage
test-coverage: ## Generate test coverage report
	composer test:coverage

.PHONY: ci
ci: ## Run complete CI pipeline (pre-commit checks)
	composer ci || composer ci:test

.PHONY: clean
clean: ## Clean temporary files and caches
	rm -rf .php-cs-fixer.cache
	rm -rf var/
	rm -rf .Build/.cache

# ===================================
# Extension-Specific Commands
# ===================================

.PHONY: verify
verify: ## Verify temporal cache system health
	ddev ssh -d v12 "vendor/bin/typo3 temporalcache:verify -v"

.PHONY: analyze
analyze: ## Analyze temporal content (7 days)
	ddev ssh -d v12 "vendor/bin/typo3 temporalcache:analyze --days=7"

.PHONY: list-content
list-content: ## List temporal content
	ddev ssh -d v12 "vendor/bin/typo3 temporalcache:list --upcoming --format=table"

.PHONY: harmonize-preview
harmonize-preview: ## Preview harmonization changes (dry-run)
	ddev ssh -d v12 "vendor/bin/typo3 temporalcache:harmonize --dry-run"

.PHONY: flush-v12
flush-v12: ## Flush TYPO3 v12 caches
	ddev ssh -d v12 "vendor/bin/typo3 cache:flush"

.PHONY: flush-v13
flush-v13: ## Flush TYPO3 v13 caches
	ddev ssh -d v13 "vendor/bin/typo3 cache:flush"

.PHONY: flush-all
flush-all: ## Flush all TYPO3 caches (v12 + v13)
	@$(MAKE) flush-v12
	@$(MAKE) flush-v13

.PHONY: backend-v12
backend-v12: ## Open TYPO3 v12 backend in browser
	@echo "Opening: https://v12.temporal-cache.ddev.site/typo3/"
	@which xdg-open >/dev/null 2>&1 && xdg-open https://v12.temporal-cache.ddev.site/typo3/ || \
	 which open >/dev/null 2>&1 && open https://v12.temporal-cache.ddev.site/typo3/ || \
	 echo "Please open: https://v12.temporal-cache.ddev.site/typo3/"

.PHONY: backend-v13
backend-v13: ## Open TYPO3 v13 backend in browser
	@echo "Opening: https://v13.temporal-cache.ddev.site/typo3/"
	@which xdg-open >/dev/null 2>&1 && xdg-open https://v13.temporal-cache.ddev.site/typo3/ || \
	 which open >/dev/null 2>&1 && open https://v13.temporal-cache.ddev.site/typo3/ || \
	 echo "Please open: https://v13.temporal-cache.ddev.site/typo3/"

.PHONY: urls
urls: ## Show all access URLs
	@echo ""
	@echo "TYPO3 Temporal Cache - Access URLs"
	@echo "==================================="
	@echo ""
	@echo "TYPO3 v12.4 LTS:"
	@echo "  Frontend: https://v12.temporal-cache.ddev.site/"
	@echo "  Backend:  https://v12.temporal-cache.ddev.site/typo3/"
	@echo ""
	@echo "TYPO3 v13.0 LTS:"
	@echo "  Frontend: https://v13.temporal-cache.ddev.site/"
	@echo "  Backend:  https://v13.temporal-cache.ddev.site/typo3/"
	@echo ""
	@echo "Mailpit (Email Testing):"
	@echo "  URL: https://temporal-cache.ddev.site:8026/"
	@echo ""
	@echo "Backend Credentials:"
	@echo "  Username: admin"
	@echo "  Password: Password:joh316"
	@echo ""

.PHONY: deep-clean
deep-clean: stop ## Complete cleanup (stop + remove installations)
	@echo "⚠️  This will remove all TYPO3 installations!"
	@read -p "Continue? [y/N] " -n 1 -r; \
	echo; \
	if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
		rm -rf v12 v13; \
		echo "✅ Cleanup complete. Run 'make up' to reinstall."; \
	else \
		echo "Cancelled."; \
	fi

.DEFAULT_GOAL := help
